-- AlterTable
ALTER TABLE "public"."User" ALTER COLUMN "phone" DROP DEFAULT,
ALTER COLUMN "streetAddress" DROP DEFAULT,
ALTER COLUMN "postalCode" DROP DEFAULT,
ALTER COLUMN "city" DROP DEFAULT,
ALTER COLUMN "country" DROP DEFAULT;
