/* eslint-disable @typescript-eslint/no-explicit-any */
import "./globals.css";
import type { Metadata } from "next";
import { Cairo, Roboto } from "next/font/google";
import {NextIntlClientProvider} from 'next-intl';
import {getMessages} from 'next-intl/server';
import {notFound} from 'next/navigation';
import {routing} from '@/i18n/routing';
import Footer from '@/components/footer';
import Header from '@/components/Header';
import ReduxProvider from "@/Provider/ReduxProvider";
import { Directions, Languages } from "@/constants/enums";
import { Toaster } from "@/components/ui/sonner"
import Providers from "@/Provider/SessionProvider";




const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  preload: true,
});

const cairo = Cairo({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default async function LocaleLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: Promise<{locale: string}>;
}) {
  // Ensure that the incoming `locale` is valid
  const {locale} = await params;
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }
 
  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();
 
  return (
    <html 
    lang={locale}
    dir={locale === Languages.ARABIC ? Directions.RTL : Directions.LTR}
    >
      <body
        className={
          locale === Languages.ARABIC ? cairo.className : roboto.className
        }
      >
        <NextIntlClientProvider messages={messages}>
        <Providers>
        <ReduxProvider>
        <Header />
          {children}
          <Toaster richColors position="top-center"  />
          <Footer />
        </ReduxProvider>
        </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}